# Generated by Django 4.2.4 on 2023-09-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0002_author_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='Author/', verbose_name='', width_field=100),
        ),
    ]
